apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/managed-by: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HireReady381/eks-argocd-project
    targetRevision: HEAD
    path: helm/charts/payment-service

  destination:
    server: https://kubernetes.default.svc
    namespace: payment-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
