# ArgoCD Helm Values
# Chart: argo-cd | https://argoproj.github.io/argo-helm

global:
  domain: argocd.example.com

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  replicas: 1

controller:
  replicas: 1

redis:
  enabled: true

notifications:
  enabled: false
